"""Remove image_url and update User primary key

Revision ID: 7b802f5f14e7
Revises: 7fd39c2bd88e
Create Date: 2024-12-01 20:03:42.554152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b802f5f14e7'
down_revision: Union[str, None] = '7fd39c2bd88e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove 'image_url' column from all relevant tables
    with op.batch_alter_table('photo_card') as batch_op:
        batch_op.drop_column('image_url')
    with op.batch_alter_table('passport') as batch_op:
        batch_op.drop_column('image_url')
    with op.batch_alter_table('driver_license') as batch_op:
        batch_op.drop_column('image_url')

    # Alter 'users' table to drop 'id' column and make 'email' the primary key
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_index('ix_users_id')  # Drop index on 'id'
        batch_op.drop_column('id')         # Drop the 'id' column
        batch_op.create_primary_key('pk_users_email', ['email'])  # Set 'email' as the primary key
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Re-add 'image_url' column to all relevant tables
    with op.batch_alter_table('photo_card') as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
    with op.batch_alter_table('passport') as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
    with op.batch_alter_table('driver_license') as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # Revert changes to 'users' table
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_constraint('pk_users_email', type_='primary')  # Drop primary key on 'email'
        batch_op.add_column(sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True))
        batch_op.create_index('ix_users_id', ['id'])  # Recreate index on 'id'
    # ### end Alembic commands ###
