# Generated by Django 5.1.3 on 2024-11-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DriverLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(max_length=50, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("address", models.TextField()),
                ("gender", models.CharField(max_length=20)),
                ("expiry_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Passport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passport_number", models.CharField(max_length=50, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("nationality", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(max_length=20)),
                ("expiry_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="PhotoCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("photo_card_number", models.CharField(max_length=50, unique=True)),
                ("date_of_birth", models.DateField()),
                ("card_number", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=20)),
                ("expiry_date", models.DateField()),
            ],
        ),
    ]
