version: "3.11"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:12345678@35.222.190.97:5432/test1
    depends_on:
      - db
    volumes:
      - .:/app
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: test1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
