"""Add image_url columns

Revision ID: a8422efa702a
Revises: 
Create Date: 2024-11-25 22:42:16.981377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8422efa702a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add `image_url` column to the `photo_card` table
    op.add_column('photo_card', sa.Column('image_url', sa.String(), nullable=True))

    # Add `image_url` column to the `passport` table
    op.add_column('passport', sa.Column('image_url', sa.String(), nullable=True))

    # Add `image_url` column to the `driver_license` table
    op.add_column('driver_license', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove `image_url` column from the `photo_card` table
    op.drop_column('photo_card', 'image_url')

    # Remove `image_url` column from the `passport` table
    op.drop_column('passport', 'image_url')

    # Remove `image_url` column from the `driver_license` table
    op.drop_column('driver_license', 'image_url')
    # ### end Alembic commands ###
