name: scan_ml_text_kit
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  google_mlkit_text_recognition: ^0.14.0
  camera: 0.11.0
  permission_handler: ^11.4.0
  http: ^1.3.0
  logger: ^2.5.0
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.2.1
  gap: ^3.0.1
  email_validator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true

  # Asset management
  assets:
    - assets/
    - assets/images/
    - assets/images/logo.png
    - assets/images/bg1.png
